"""create_initial_tables

Revision ID: 0fc2f94ed2e6
Revises: 251a8f06a3b0
Create Date: 2025-11-27 09:23:59.368455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc2f94ed2e6'
down_revision: Union[str, None] = '251a8f06a3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
