"""add contractor_name and work_date to job

Revision ID: 161258c6753a
Revises: e6d7c7b38e20
Create Date: 2025-12-05 01:02:41.110286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161258c6753a'
down_revision: Union[str, None] = 'e6d7c7b38e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('contractor_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('work_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'work_date')
    op.drop_column('jobs', 'contractor_name')
    # ### end Alembic commands ###
