"""empty message

Revision ID: 18ca1bc75cb1
Revises: dd2f7e6acb07
Create Date: 2025-12-08 05:52:08.367280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ca1bc75cb1'
down_revision: Union[str, None] = 'dd2f7e6acb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
