"""empty message

Revision ID: 2e43ec49124e
Revises: cb53bbccd187
Create Date: 2025-12-11 04:29:28.425151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e43ec49124e'
down_revision: Union[str, None] = 'cb53bbccd187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('cover_title', sa.String(length=255), nullable=True))
    op.add_column('export_jobs', sa.Column('cover_company_name', sa.String(length=255), nullable=True))
    op.add_column('export_jobs', sa.Column('labels', sa.JSON(), nullable=True))
    op.drop_column('export_jobs', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('export_jobs', 'labels')
    op.drop_column('export_jobs', 'cover_company_name')
    op.drop_column('export_jobs', 'cover_title')
    # ### end Alembic commands ###
