"""create_initial_tables

Revision ID: 3b517e37f7c5
Revises: f6d4f550ccd4
Create Date: 2025-11-27 09:20:27.550149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b517e37f7c5'
down_revision: Union[str, None] = 'f6d4f550ccd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
