"""empty message

Revision ID: 5346d5dd0ebe
Revises: 913c3ec7dfa9
Create Date: 2025-12-20 09:40:13.412092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5346d5dd0ebe'
down_revision: Union[str, None] = '913c3ec7dfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
