"""empty message

Revision ID: 6fbb1ca62fcc
Revises: 30a513252fcb
Create Date: 2025-12-06 11:48:49.233846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fbb1ca62fcc'
down_revision: Union[str, None] = '30a513252fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('construction_type', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.drop_column('jobs', 'contractor_name')
    op.drop_column('jobs', 'work_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('work_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('contractor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'company_name')
    op.drop_column('jobs', 'construction_type')
    # ### end Alembic commands ###
