"""empty message

Revision ID: 848f1cc17bfe
Revises: b4cbe1fc601a
Create Date: 2025-12-20 08:49:50.091138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848f1cc17bfe'
down_revision: Union[str, None] = 'b4cbe1fc601a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
