"""empty message

Revision ID: 897cef836439
Revises: dd17a3d6a033
Create Date: 2025-12-05 00:54:41.617703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897cef836439'
down_revision: Union[str, None] = 'dd17a3d6a033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
