"""empty message

Revision ID: 90a0cdd2766d
Revises: ccb0cb5f5768
Create Date: 2025-12-04 01:36:30.071197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a0cdd2766d'
down_revision: Union[str, None] = 'ccb0cb5f5768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
