"""empty message

Revision ID: cb53bbccd187
Revises: 59703199b3ce
Create Date: 2025-12-11 03:45:48.511914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb53bbccd187'
down_revision: Union[str, None] = '59703199b3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'config')
    # ### end Alembic commands ###
