"""empty message

Revision ID: fe02611fd1c6
Revises: c3f73ea0b46e
Create Date: 2025-12-10 08:19:46.825417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe02611fd1c6'
down_revision: Union[str, None] = 'c3f73ea0b46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'labels')
    # ### end Alembic commands ###
